[package]
name = "adapter"
version.workspace = true
edition.workspace = true

[dependencies]
domain.workspace = true
storage.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
matrix-sdk.workspace = true
chrono.workspace = true
serde_json.workspace = true
